# 🐦 **Sử dụng LangChain để xây dụng quá trình Word Embedding**

## 📑 **Khái niệm**

- **LLM (Ngôn ngữ lớn)**

Là các mô hình AI được huấn luyện trên lượng dữ liệu văn bản cực lớn dể hiểu và tạo ra các ngôn ngữ tự nhiên

Ví dụ: *ChatGPT, GPT, Gemini*

Học bằng cách: Đọc rấy nhiều văn ban, học cách dự đoán từ tiếp theo trong câu

- **Vector Search**

Là cách tìm kiếm dựa trên ý nghĩa thay vì chỉ từ khóa

**Ý tưởng**

```
  - Mỗi đoạn văn / câu / từ được biến thành vector (một dãy số)
  - Những nội dung có ý nghĩa giống nhau -> vector sẽ gần nhau
```

**Vector trông như thế nào**

```
"king"  → [0.25, -0.11, 0.78, ...]
"queen" → [0.27, -0.10, 0.80, ...]
```

Hai vector gần nhau sẽ giống nhau

- **Word2Vec**
  - Là một trong những kỹ thuật nền tảng giúp máy tính hiểu ý nghĩa của từ bằng cách biến từ thành vector (Là mô hình do Google phát triển).
  - Ý tưởng là học từ ngữ cảnh của từ:
  ```
  Ví dụ: "Tôi nuôi một con mèo"
  
  Mô hình sẽ học:
   - "mèo" thường xuất hiện gần "nuôi", "con"
   - từ đó hiểu ý nghĩa của từ "mèo"
  ```
  - Hai cách huán luyện chính:
    - CBOW: Đoán từ ở giữa dựa vào từ xung quanh
    - Skip-gram: Từ trung tam đoán từ xung quanh

⇒ **Word2Vec sẽ biến các từ thành các vector sau đó sử dụng VectorSearch để tìm kiếm các từ cùng nghĩa**

---

## 🎰 **Kỹ thuật**

### ✂️ **Chia nhỏ văn bản hình thành vector database**

**Pipeline:**

```
Load tài liệu ->  Cắt nhỏ tài liệu -> Lưu và vector database
```

- **TextLoader**: Đọc file txt -> Biến text thành nội dung mà LangChain hiểu được

> Là bước lấy dữ liệu thô vào hệ thống AI

- **CharacterTextSplitter**: Chia nhỏ văn bản (cắt đoạn dài thành nhiều đoạn nhỏ)

- **Chroma**: Lưu các đoạn văn dưới dạng vector và cho phép tìm kiếm theo ngữ nghĩa

### 🧠 **Xây dựng Hệ thống**

**Pipeline**

```
Lây vector trong database -> Lưu và tìm kiếm vector tương đồng
```

- **HuggingFaceEmbeddings:** Biến text thành vector
- **Chroma:** Lưu và tìm kiếm vector -> so sánh vector và trả về đoạn giống nhất

### 🧩 **Flow hoàn chính trong notebook**

```
- Lớp biến đổi

File csv -> Chuyển thành file text -> Chia nhỏ văn bản -> Embedding - Chuyển văn bản thành vector (Hugging Face) -> Lưu vào vector database (Chroma)

- Lớp truy vấn

Query -> Embedding (vector) -> So sánh cosine similarity -> Top K kết quả

```

In [ ]:
!pip install langchain langchain_community langchain_chroma

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.12)
Requirement already satisfied: langchain_community in /usr/local/lib/python3.12/dist-packages (0.4.1)
Requirement already satisfied: langchain-openai in /usr/local/lib/python3.12/dist-packages (1.1.11)
Requirement already satisfied: cohere in /usr/local/lib/python3.12/dist-packages (5.20.7)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (0.12.0)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (1.2.2)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.19)
Requirement already satisfied: langgraph<1.2.0,>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.1.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (1.0.3)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.0.48)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (9.1.4)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.13.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (0.7.18)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.0.2)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (2.28.0)
Requirement already satisfied: fastavro<2.0.0,>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from cohere) (1.12.1)
Requirement already satisfied: httpx>=0.21.2 in /usr/local/lib/python3.12/dist-packages (from cohere) (0.28.1)
Requirement already satisfied: pydantic-core>=2.18.2 in /usr/local/lib/python3.12/dist-packages (from cohere) (2.41.4)
Requirement already satisfied: tokenizers<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from cohere) (0.22.2)
Requirement already satisfied: types-requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cohere) (2.32.4.20260107)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from cohere) (4.15.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken) (2025.11.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.23.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (0.9.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->cohere) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->cohere) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->cohere) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->cohere) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.21.2->cohere) (0.16.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain_community) (1.1.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (26.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain) (4.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain) (1.0.8)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain) (0.3.11)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain) (3.6.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.25.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (0.13.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (4.67.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2.5.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain_community) (3.3.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers<1,>=0.15->cohere) (1.7.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (1.4.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (0.24.1)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.0.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.1->langchain) (1.12.2)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain_community) (1.1.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (0.1.2)

# ✂️ **Chia nhỏ văn bản hình thành vector database**

In [ ]:
from langchain_community.document_loaders import TextLoader # Load văn bản để LangChain có thể làm việc
from langchain_text_splitters import CharacterTextSplitter # Chia nhỏ thành phần để Huấn luyện
from langchain_chroma import Chroma

In [ ]:
import pandas as pd

df = pd.read_csv('books_cleaned.csv')
df.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."

In [ ]:
df['tagged_description']

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: object

In [ ]:
df['tagged_description'].to_csv('tagged_description.txt',
                                sep = "\n",
                                index = False,
                                header = False)

In [ ]:
raw_doc = TextLoader('tagged_description.txt').load()
text_splitter = CharacterTextSplitter(chunk_size = 1,
                                      chunk_overlap = 0,
                                      separator="\n")

doc = text_splitter.split_documents(raw_doc)

Streaming output truncated to the last 5000 lines.
WARNING:langchain_text_splitters.base:Created a chunk of size 1483, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 221, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1135, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 722, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 668, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 765, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 606, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 570, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 965, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 857, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1032, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 189, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 367, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 495, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 652, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 348, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 733, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 525, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1015, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 970, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 204, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 688, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 544, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 242, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 207, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 376, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 931, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 564, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 854, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 715, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 749, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 712, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 324, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 241, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1088, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 723, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 245, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 227, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 704, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1912, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 395, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 485, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 622, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 559, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 556, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 386, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 229, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 425, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 418, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 284, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 166, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 624, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 2616, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1580, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 389, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 994, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 847, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 263, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 336, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1530, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 213, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 291, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 2030, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 396, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1619, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 698, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 822, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 354, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 843, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1189, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 195, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 508, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 663, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1282, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 260, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 242, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 215, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 198, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1268, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1277, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 198, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1056, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 378, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 269, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 177, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 225, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 222, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 784, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 969, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 613, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 163, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 757, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 289, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 245, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 963, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 232, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 843, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 786, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 648, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 984, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 799, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 193, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1163, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 253, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 203, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1058, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 246, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 875, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 817, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 378, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 755, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 569, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 628, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 868, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 620, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 621, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1084, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 2762, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1033, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 758, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 773, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 634, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1010, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 189, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1064, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 492, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 795, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 699, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 485, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 372, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 275, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1224, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 223, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 345, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 657, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 199, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 767, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 553, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 227, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 233, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 590, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 238, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 299, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 726, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1805, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1017, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 684, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 739, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 236, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 449, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 472, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 922, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 220, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 162, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 967, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 477, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 220, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 645, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 676, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 712, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 799, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 854, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 670, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 211, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 854, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 275, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 760, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 796, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 679, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 927, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1268, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 733, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 868, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 931, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 772, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 770, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 335, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 649, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 1771, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 534, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 824, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 261, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 599, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 486, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 969, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 275, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 554, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 491, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 844, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 876, which is longer than the specified 1
WARNING:langchain_text_splitters.base:Created a chunk of size 670, which is longer than the specified 1

# 🧠 **Xây dựng Hệ thống**

In [ ]:
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

embedding = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# tạo vector DB
db_books = Chroma.from_documents(doc, embedding=embedding)

/tmp/ipykernel_2384/648914237.py:5: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embedding = HuggingFaceEmbeddings(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [44]:
embedding = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    encode_kwargs={"batch_size": 32}
)

query = "A book to teach children about nature"

results = db_books.similarity_search(query, k=5)

for r in results:
    print(r.page_content)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.
9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects.
9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects.
9780060959036 Barbara Kingsolver's fifth novel is a hymn to wildness that celebrates the prodigal spirit of human nature, and of nature itself. It weaves together three stories of human love within a larger tapestry of lives amid the mountains and farms of southern Appalachia. Over the course of one humid summer, this novel's intriguing protagonists face disparate predicaments but find connections to one another and to the flora and fauna with which they necessarily share a place.
9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects.

In [48]:
df[df['isbn13'] == int(results[0].page_content.split()[0].strip())] # Kết quả

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [64]:
def retrive_sematic_recommendations(query: str, top_k: int) -> pd.DataFrame: # Dựng hàm recommendation
    results = db_books.similarity_search(query, k=50)

    books_list = []
    for i in range(len(results)):
        raw = results[i].page_content.strip().split()[0]
        clean = raw.strip('"')
        books_list.append(int(clean))

    return df[df['isbn13'].isin(books_list)].head(top_k)

In [65]:
retrive_sematic_recommendations("A book to teach children about nature", 5)

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
59,9780007151240,0007151241,The Family Way,Tony Parsons,Parenthood,http://books.google.com/books/content?id=dJEIx...,It should be the most natural thing in the wor...,2005.0,3.51,400.0,2095.0,The Family Way,9780007151240 It should be the most natural th...
324,9780060959036,0060959037,Prodigal Summer,Barbara Kingsolver,Fiction,http://books.google.com/books/content?id=06IwG...,Barbara Kingsolver's fifth novel is a hymn to ...,2001.0,4.00,444.0,85440.0,Prodigal Summer: A Novel,9780060959036 Barbara Kingsolver's fifth novel...
334,9780060976118,006097611X,Operation Wandering Soul,Richard Powers,Fiction,http://books.google.com/books/content?id=nIGIm...,"Highly imaginative and emotionally powerful, t...",1994.0,3.62,352.0,366.0,Operation Wandering Soul,9780060976118 Highly imaginative and emotional...
383,9780061144899,0061144894,When the Heart Waits,Sue Monk Kidd,Religion,http://books.google.com/books/content?id=JlP91...,From the Bestselling Author of The Secret Life...,2006.0,4.17,240.0,2141.0,When the Heart Waits: Spiritual Direction for ...,9780061144899 From the Bestselling Author of T...
404,9780064402453,0064402452,Racso and the Rats of NIMH,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=MgoNv...,"‘Racso, a brash and boastful little rodent, is...",1988.0,3.76,288.0,3231.0,Racso and the Rats of NIMH,"9780064402453 ‘Racso, a brash and boastful lit..."